services:
  #CatalogDB 27017:27017
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

  #Catalog.API 9000:8080
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # __ instead of : because of the way the environment variables are parsed in the .NET Core configuration system
      # DatabaseSettings__ConnectionString means DatabaseSettings:ConnectionString in the appsettings.json file
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
      - elasticsearch
    ports:
      # 8080 : docker file
      # 9000 local machine
      - "9000:8080"
  
  #BasketDB 6379:6379
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  #Basket.API 9001:8080
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Redis=basketdb:6379"
      - ASPNETCORE_URLS=http://*:8080
      - "GrpcSettings__DiscountUrl=http://discount.api:8080"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    ports:
      - "9001:8080"
    depends_on:
      - basketdb
      - rabbitmq
      - elasticsearch
  
  #discountdb 5432:5432
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  #postgresAdmin 5050:80
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eCommerce.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  #Discount.API 9002:8080
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
       elasticsearch:
          condition: service_started
       discountdb:
          condition: service_healthy
    ports:
      - "9002:8080"

  #OrderDB 1433:1433
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "Alich1234567"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Alich1234567' -Q 'select 1'"]
      interval: 10s
      timeout: 10s
      retries: 3
 
  #RabbitMQ 15672 5672
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
    - "15672:15672"
    - "5672:5672"

  #Elasticsearch 9200:9200
  elasticsearch:
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  
  #Kibana 5601:5601
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  #ordering.api 9003:8080
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080 
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Alich1234567;TrustServerCertificate=True" 
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
     - orderdb
     - rabbitmq
     - elasticsearch
    ports:
     - "9003:8080"      
