services:
  #CatalogDB 27017:27017
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

  #Catalog.API 9000:8080
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # __ instead of : because of the way the environment variables are parsed in the .NET Core configuration system
      # DatabaseSettings__ConnectionString means DatabaseSettings:ConnectionString in the appsettings.json file
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - catalogdb
    ports:
      # 8080 : docker file
      # 9000 local machine
      - "9000:8080"
  
  #BasketDB 6379:6379
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  #Basket.API
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Redis=basketdb:6379"
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "9001:8080"
    depends_on:
      - basketdb