services:
  #OrderDb
  orderdb:
    image : mcr.microsoft.com/mssql/server:2022-latest  

  #CatalogDB
  catalogdb:
    image : mongo

  #Catalog.API
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.Api/Dockerfile
  
  #DiscountDB
  discountdb:
    image : postgres

  #postgresAdmin
  pgadmin:
    image : dpage/pgadmin4

  #BasketDB
  basketdb:
    image : redis
 
  #Basket.API
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/basket/Basket.Api/Dockerfile

  #Discount.API
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/discount/Discount.Api/Dockerfile

  #Order.API
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: services/ordering/Ordering.Api/Dockerfile
  
  #ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    
  #Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3

  #RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine

volumes:
 mongo_data:
 postgres_data:  
 pgadmin_data:
 orderdb_data:
 elasticsearch_data:
